#! /bin/sh

sxhkd &

# BSPWM behavior
bspc config border_width          3
bspc config split_ratio           0.52
bspc config window_gap            16
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true

# BSPWM colors
bspc config normal_border_color   "#2E2E2E"
bspc config active_border_color   "#5F5A60"
bspc config focused_border_color  "#1e1e1e"
bspc config urgent_border_color   "#FFFF00"
bspc config presel_feedback_color "#1e1e1e"

# BSPWM workspaces
i=0
for monitor in $(bspc query -M); do
  bspc monitor $monitor -n "${i}" -d "One" "Two" "Three" "Four" "Five" "Six" "Seven" "Eight" "Nine"
  let i++
done
unset i

# Run some scripts after starting bspwm
feh --bg-fill $HOME/.config/wallpaper.jpg &
compton --config $HOME/.config/compton.conf &


# bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config border_width         2
# bspc config window_gap          12

# bspc config split_ratio          0.52
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


